---
version: 2.1
jobs:
  build:
    docker:
      - image: quay.io/ansible/molecule:3.0.3

    # Ansible finds the role by its exact directory name
    working_directory: ~/ansible-role-girder-mongodb

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install a working version of ansible-lint
          # https://github.com/ansible-community/molecule/issues/2646
          command: pip3 install ansible-lint==4.2.0

      - run:
          name: Run Molecule
          command: molecule test

workflows:
  version: 2
  ci:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
