---
version: 2.1
jobs:
  build:
    docker:
      - image: quay.io/ansible/molecule:3.0.2

    # Ansible finds the role by its exact directory name
    working_directory: ~/ansible-role-girder-mongodb

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run Molecule
          command: molecule test

workflows:
  version: 2
  ci:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
